services:
  - type: web
    name: mern-student-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://mern-student-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html